# Generated by Django 6.0.3 on 2026-04-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('preset', 'Preset'), ('manual', 'Manual'), ('saved_setup', 'Saved Setup')], default='manual', max_length=20)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
    ]
