# Generated by Django 6.0.3 on 2026-04-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terpenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terpene',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
