# Generated by Django 6.0.3 on 2026-04-07 19:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects', '0001_initial'),
        ('states', '0001_initial'),
        ('terpenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('strain_type', models.CharField(choices=[('indica', 'Indica'), ('sativa', 'Sativa'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('flavor_profile', models.CharField(blank=True, help_text='Example: sweet, creamy, vanilla, earthy', max_length=255)),
                ('aroma_profile', models.CharField(blank=True, help_text='Example: citrus, diesel, pine, floral', max_length=255)),
                ('thc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('thc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cbd_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cbd_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('breeder', models.CharField(blank=True, max_length=150)),
                ('lineage', models.CharField(blank=True, help_text='Example: Blueberry x Haze', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strain',
                'verbose_name_plural': 'Strains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrainEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect_strain_links', to='effects.effect')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_effect_links', to='strains.strain')),
            ],
            options={
                'verbose_name': 'Strain Effect',
                'verbose_name_plural': 'Strain Effects',
                'ordering': ['-score', 'effect__name'],
                'unique_together': {('strain', 'effect')},
            },
        ),
        migrations.AddField(
            model_name='strain',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='strains', through='strains.StrainEffect', to='effects.effect'),
        ),
        migrations.CreateModel(
            name='StrainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('best_time_of_day', models.CharField(blank=True, help_text='Example: morning, afternoon, late-night', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_strain_links', to='states.creativestate')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_state_links', to='strains.strain')),
            ],
            options={
                'verbose_name': 'Strain State',
                'verbose_name_plural': 'Strain States',
                'ordering': ['-score', 'state__name'],
                'unique_together': {('strain', 'state')},
            },
        ),
        migrations.AddField(
            model_name='strain',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='strains', through='strains.StrainState', to='states.creativestate'),
        ),
        migrations.CreateModel(
            name='StrainTerpene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prominence', models.DecimalField(decimal_places=2, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_terpene_links', to='strains.strain')),
                ('terpene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terpene_strain_links', to='terpenes.terpene')),
            ],
            options={
                'verbose_name': 'Strain Terpene',
                'verbose_name_plural': 'Strain Terpenes',
                'ordering': ['-prominence', 'terpene__name'],
                'unique_together': {('strain', 'terpene')},
            },
        ),
        migrations.AddField(
            model_name='strain',
            name='terpenes',
            field=models.ManyToManyField(blank=True, related_name='strains', through='strains.StrainTerpene', to='terpenes.terpene'),
        ),
    ]
